AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Lambda using SAM

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-lambda-function
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 10
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
